version: "3.8"
services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --legacy-peer-deps && npm start"
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"

volumes:
  postgres-data:
